# Generated by Django 6.0.2 on 2026-02-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_admin_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
