# Generated by Django 6.0.2 on 2026-02-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_employerprofile_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_email',
            field=models.EmailField(default='hr@gmail.com', max_length=254),
        ),
    ]
