# Generated by Django 6.0.2 on 2026-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_employerprofile_employer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_bio',
            field=models.TextField(default='A passionate and result-driven software developer...'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_image',
            field=models.ImageField(default='user_default.png', upload_to='user_profile/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_resume',
            field=models.FileField(default='default_resume.pdf', upload_to='user_resume/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(default='XYZ Company', max_length=200),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='employer_email',
            field=models.EmailField(default='hr@example.com', max_length=254),
        ),
    ]
