# Generated by Django 6.0.2 on 2026-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_applicantprofile_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user_education',
            field=models.CharField(default='Bachulor Passout in Computer Science from New Summit College', max_length=200),
        ),
    ]
