# Generated by Django 5.2.5 on 2026-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='static/uploads/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
