# Generated by Django 5.2.5 on 2026-01-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
