# Generated by Django 6.0.2 on 2026-02-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_applyjob_phone_alter_applyjob_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('interview', 'Interview Scheduled')], default='pending', max_length=20),
        ),
    ]
