# Generated by Django 5.2.5 on 2026-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applyjob_interview_date_applyjob_job_applyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
